CREATE TABLE `news` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `JOURNAL_ID` varchar(10) NOT NULL COMMENT '언론사 아이디',
  `TITLE` varchar(200) NOT NULL COMMENT '제목',
  `PUBLISH_DATE` varchar(20) DEFAULT NULL COMMENT '작성일',
  `LINK_URL` varchar(200) DEFAULT NULL COMMENT 'URL',
  `WRITER` varchar(20) DEFAULT NULL COMMENT '작성자',
  `CONTENT` text DEFAULT NULL COMMENT '내용',
  `REG_DATE` datetime NOT NULL COMMENT '등록일',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=198784 DEFAULT CHARSET=utf8;